services:
  - type: web
    name: thread-clone
    env: python
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      chmod +x run.sh run_gunicorn.sh
    # Sử dụng gunicorn đơn giản hơn và ổn định hơn cho Render
    startCommand: ./run_gunicorn.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: PYTHONPATH
        value: /opt/render/project/src
