# Generated by Django 4.2.4 on 2025-03-19 13:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_link_alter_myuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
