# Generated by Django 4.2.4 on 2025-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
