# Generated by Django 4.2.4 on 2025-03-19 13:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0018_notification_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='comment_images/'),
        ),
        migrations.AlterField(
            model_name='threadimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='thread_images/'),
        ),
    ]
