# Generated by Django 4.2.4 on 2025-03-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0019_alter_commentimage_image_alter_threadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
