# Generated by Django 4.2.4 on 2025-05-03 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0021_toxiccontentlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToxicContentLog',
        ),
    ]
